# Generated by Django 5.0.2 on 2024-04-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_choice_is_correct_delete_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponse',
            name='selected_choices',
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_ans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_four',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_one',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_three',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_two',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='QuizResponse',
        ),
    ]
